### ISSUE TITLE
aptSetSleepAllowed() doesn't make network to stay alive when called

### ISSUE THREAD

**Issue by TheBaloneyboy** [devkitPro/libctru#286]
When an application set aptSetSleepAllowed to false, and the lid is closed, network services are still set to sleep, even if an application is running. An example of this would be FBI. When installing a title off of CDN/Network and closing the lid, the install aborts due to network disconnection. Not sure what can be done about this.

**Comment by Aridez** [comment]
I'm still having this problem, are there any workarounds?

**Comment by profi200** [comment]
Could have to do with the RunnableOnSleep flag in the exheader. Not sure what it is set to for 3dsx aps.

**Comment by fincs** [comment]
The desired behavior can be achieved using the NDM service, as done by Rosalina here: https://github.com/LumaTeam/Luma3DS/blob/master/sysmodules/rosalina/source/minisoc.c#L58-L91
