### ISSUE TITLE
The site at libctru.devkitpro.org still contains a link to smealum.github.io

### ISSUE THREAD

**Issue by psidex** [devkitPro/libctru#465]
https://libctru.devkitpro.org/

> The documentation is automatically built upon release and can be found at the following url: http://smealum.github.io/ctrulib

Shouldn't this be

> The documentation is automatically built upon release and can be found at the following url: https://devkitpro.github.io/libctru

**Comment by Oreo639** [comment]
It will be updated when the documentation is rebuilt for the next libctru release.

**Comment by fincs** [comment]
Closing, because it will be automatically fixed anyway like @Oreo639 said. Hopefully we can sort out a release soon, stay tuned ( ͡° ͜ʖ‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌├┬┴┬┴
