### ISSUE TITLE
CFGU_GetSystemModel not working?

### ISSUE THREAD

**Issue by mkst** [devkitPro/libctru#475]
Hi Guys,

The `CFGU_GetSystemModel` method does not seem to return the model correctly.

Example code (taken from examples)

```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <3ds.h>

int main(int argc, char* argv[])
{
    gfxInitDefault();
    consoleInit(GFX_TOP, NULL);

    u8 model = 0;
    Result res = CFGU_GetSystemModel(&model);
    printf("Result: %li, Your xDS Model is: %i\n", res, model);

    // Main loop
    while (aptMainLoop())
    {
        gspWaitForVBlank();
        gfxSwapBuffers();
        hidScanInput();

        // Your code goes here
        u32 kDown = hidKeysDown();
        if (kDown & KEY_START)
            break; // break in order to return to hbmenu
    }

    gfxExit();
    return 0;
}
```

When ran on my N3DS gives me:

```
Result: -656406537, Your xDS Model is: 0
```

This is with devkitpro, pretty vanilla stuff.

**Comment by SciresM** [comment]
You aren't calling cfguInit, so you're getting an error code when trying to use cfgu service commands.

You need to initialize the service (and exit it when you're done).

Also, you probably want to print results as hex (%08x), they're not signed integers.

**Comment by mkst** [comment]
Wonderful, thanks for the swift answer!
