### ISSUE TITLE
Memory access out-of-bounds while using std::cout

### ISSUE THREAD

**Issue by FurryR** [devkitPro/libctru#519]
Example:
```cpp
#include <iostream>
int main() {
  int x = 25, y = 25;
  std::cout << "\x1b[" + std::to_string(y) + ";" + std::to_string(x) + "H"; // works properly
  std::cout << "\x1b[" << y << ";" << x << "H"; // ???
}
```
Result:
![Result](https://user-images.githubusercontent.com/55276797/227757857-8cf492a7-b462-4d88-9e3b-cad49b731672.png)
Is it "unbuffered" or something else? :/

**Comment by mtheall** [comment]
Yes this is because iostream is unbuffered. You must output the entire escape sequence in a single operation for them to work
