### ISSUE TITLE
Where is sockaddr_in6 defined?

### ISSUE THREAD

**Issue by tendstofortytwo** [devkitPro/libctru#529]
Trying to compile libressl for the 3DS, ran into not having definitions for the constant `SOMAXCONN` (I just defined this to be 128 via CFLAGS) and `struct sockaddr_in6`. The IPv4 equivalent is defined in netinet/in.h, was wondering where the IPv6 version is, if it exists?

**Comment by WinterMute** [comment]
There's no ipv6 support in Horizon, sorry.

**Comment by tendstofortytwo** [comment]
Ah, thanks. For anyone else looking for something similar as me, BearSSL compiles fairly easily for the 3DS without the need for IPv6.

**Comment by WinterMute** [comment]
We supply mbedtls precompiled for 3ds via https://github.com/devkitPro/pacman

**Comment by tendstofortytwo** [comment]
Thanks! I missed that because I was searching for SSL. Appreciate it.
