### ISSUE TITLE
GPU Command Buffer Causes Crash When Filled/Overran

### ISSUE THREAD

**Issue by Wyatt-James** [devkitPro/libctru#545]
### What's the issue you encountered?

Sending too many GPU commands causes a GPU command buffer overrun and a crash.

### How can the issue be reproduced?

Send enough GPU commands to overrun the command buffer. Updating uniforms and sending tris should be sufficient.

### Environment?

- What host OS are you using?
Win10 22H2 x64, with the 3DS executable built on WSL2 Ubuntu 22.04 LTS using Docker
- Official release or unofficial/self-compiled build: 
The release present in [devkitpro/devkitarm:20240202,](https://hub.docker.com/layers/devkitpro/devkitarm/20240202/images/sha256-2ee5e6ecdc768aa7fb8f2e37be2e27ce33299e081caac20a0a2675cdc791cf32?context=explore) which I believe to be official

### Additional context?

Should this not be a circular buffer, with a stall to wait for the GPU if it is filled? I understand if this is not possible, in which case this issue should be closed, but that feels unlikely. Rendering stereoscopic 3D can be quite expensive, since it demands replicating each draw call with two P-matrices. If there are a lot of draw calls and graphics data is structured in a rather unfortunate manner, the number of uniform sets can skyrocket.

The crash is caused intentionally by GPUCMD_AddInternal in [gpu.c, line 28](https://github.com/devkitPro/libctru/blob/faf5162b60eab5402d3839330f985b84382df76c/libctru/source/gpu/gpu.c#L28).

If the behavior cannot be fixed, moving the svcBreak call to a separate named function would likely help debugging without affecting performance at all, since it will crash anyway, but the function name would be provided in the callstack. Ideally it would also discriminate between the buffer NULL check and the overrun, which should be possible without a performance hit.

**Comment by mtheall** [comment]
Call C3D_Init with a larger command buffer size
For example in ftpd:
```cpp
	// initialize citro3d
	C3D_Init (2 * C3D_DEFAULT_CMDBUF_SIZE);
```
