### ISSUE TITLE
httpcCloseContext doesn't return on real 3DS

### ISSUE THREAD

**Issue by celcodioc** [devkitPro/libctru#82]
It seems that my 3DS (9.2.0-20, Ninjhax) freezes whenever a httpc context is closed with `httpcCloseContext`, even in the HTTP example in this repo. To make sure, I placed this code after the call and nothing came up:

``` c
printf("Closed context!");
gfxFlushBuffers();
```

On 3dmoo, it does not crash, however this is shown in the log:

```
>> svcSendSyncRequest (0x32)
http_c_SyncRequest (line 217): CloseContext 0dadbb17 --stub--

>> svcCloseHandle (0x23)
svcCloseHandle: svcCloseHandle undefined for handle-type "service".
```

Would be great if this could be solved.

**Comment by filfat** [comment]
This explains the problems I have with DownloadMii. +1

**Comment by yellows8** [comment]
That's not a "crash", the current thread just doesn't return from svcSendSyncRequest since the HTTP sysmodule doesn't send a command-reply.

**Comment by NamedKitten** [comment]
I have the same issue.

**Comment by fincs** [comment]
Closing, because the HTTPC service is unusable in 2020 anyway due to newer TLS protocols not being supported.
